// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsxrwpvuqeuftjjlniep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzeHJ3cHZ1cWV1ZnRqamxuaWVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxNDc1MjUsImV4cCI6MjA3NzcyMzUyNX0.hdUM1QyfgwQHU2Oq6V2PuhAZV3rCAaegMbjUMg-Jsxo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});