// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://defurrurcwefokbbbknz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlZnVycnVyY3dlZm9rYmJia256Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYzMjg1OTIsImV4cCI6MjA5MTkwNDU5Mn0.qrZrXtdTjsxug7x7hMZLm47fjc87CwT-H6ZZThaPtHw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});